/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frame;

import control.FindController;
import java.awt.Dialog;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.BorderFactory;
import javax.swing.ButtonGroup;
import javax.swing.GroupLayout;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JRadioButton;
import javax.swing.JTextField;
import javax.swing.LayoutStyle;
import javax.swing.WindowConstants;

/**
 *
 * @author MSI
 */
public class FindFrame extends javax.swing.JDialog{

    FindController control;
    
    public FindFrame(FindController control, JFrame parent) {
        super(parent);
        initComponents();
        this.control = control;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new ButtonGroup();
        jLabel1 = new JLabel();
        txtFind = new JTextField();
        btFind = new JButton();
        jPanel1 = new JPanel();
        radioUp = new JRadioButton();
        radioDown = new JRadioButton();
        btCancel = new JButton();
        checkMatch = new JCheckBox();

        setDefaultCloseOperation(WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Find");
        setResizable(false);

        jLabel1.setText("Find what:");

        btFind.setText("Find Next");
        btFind.setEnabled(false);
        btFind.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                btFindActionPerformed(evt);
            }
        });

        jPanel1.setBorder(BorderFactory.createTitledBorder("Direction"));

        buttonGroup1.add(radioUp);
        radioUp.setText("Up");

        buttonGroup1.add(radioDown);
        radioDown.setSelected(true);
        radioDown.setText("Down");

        GroupLayout jPanel1Layout = new GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(radioUp)
                .addGap(28, 28, 28)
                .addComponent(radioDown)
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(radioUp)
                    .addComponent(radioDown)))
        );

        btCancel.setText("Cancel");
        btCancel.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                btCancelActionPerformed(evt);
            }
        });

        checkMatch.setText("Match case");

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(txtFind))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(checkMatch)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(btFind, GroupLayout.Alignment.TRAILING)
                    .addComponent(btCancel, GroupLayout.Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, 85, GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFind, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(btFind))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(checkMatch))
                    .addComponent(btCancel)
                    .addComponent(jPanel1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btCancelActionPerformed(ActionEvent evt) {//GEN-FIRST:event_btCancelActionPerformed
        control.btCancel();
    }//GEN-LAST:event_btCancelActionPerformed

    private void btFindActionPerformed(ActionEvent evt) {//GEN-FIRST:event_btFindActionPerformed
        control.btFind();
    }//GEN-LAST:event_btFindActionPerformed

    /**
     * @param args the command line arguments
     */

    public JCheckBox getCheckMatch() {
        return checkMatch;
    }

    public JRadioButton getRadioDown() {
        return radioDown;
    }

    public JRadioButton getRadioUp() {
        return radioUp;
    }

    public JTextField getTxtFind() {
        return txtFind;
    }

    public JButton getBtFind() {
        return btFind;
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JButton btCancel;
    private JButton btFind;
    private ButtonGroup buttonGroup1;
    private JCheckBox checkMatch;
    private JLabel jLabel1;
    private JPanel jPanel1;
    private JRadioButton radioDown;
    private JRadioButton radioUp;
    private JTextField txtFind;
    // End of variables declaration//GEN-END:variables
}
