/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frame;

import control.ReplaceController;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.GroupLayout;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.LayoutStyle;
import javax.swing.WindowConstants;

/**
 *
 * @author MSI
 */
public class ReplaceFrame extends javax.swing.JDialog {

    ReplaceController control;
    
    public ReplaceFrame(ReplaceController control, JFrame parent) {
        super(parent);
        initComponents();
        this.control = control;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new JLabel();
        jLabel2 = new JLabel();
        txtReplace = new JTextField();
        txtFind = new JTextField();
        jPanel1 = new JPanel();
        btFind = new JButton();
        btReplace = new JButton();
        btReplaceAll = new JButton();
        btCancel = new JButton();
        checkMatch = new JCheckBox();

        setDefaultCloseOperation(WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Replace");

        jLabel1.setText("Find what:");

        jLabel2.setText("Replace with:");

        btFind.setText("Find Next");
        btFind.setEnabled(false);
        btFind.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                btFindActionPerformed(evt);
            }
        });

        btReplace.setText("Replace");
        btReplace.setEnabled(false);
        btReplace.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                btReplaceActionPerformed(evt);
            }
        });

        btReplaceAll.setText("Replace All");
        btReplaceAll.setEnabled(false);
        btReplaceAll.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                btReplaceAllActionPerformed(evt);
            }
        });

        btCancel.setText("Cancel");
        btCancel.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                btCancelActionPerformed(evt);
            }
        });

        GroupLayout jPanel1Layout = new GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(btReplace, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btFind, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btReplaceAll, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btCancel, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(btFind)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btReplace)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btReplaceAll)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btCancel))
        );

        checkMatch.setText("Match case");

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtFind, GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
                            .addComponent(txtReplace)))
                    .addComponent(checkMatch))
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtFind, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtReplace, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addComponent(checkMatch))
                    .addComponent(jPanel1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btFindActionPerformed(ActionEvent evt) {//GEN-FIRST:event_btFindActionPerformed
        control.btFind();
    }//GEN-LAST:event_btFindActionPerformed

    private void btReplaceActionPerformed(ActionEvent evt) {//GEN-FIRST:event_btReplaceActionPerformed
        control.btReplace();
    }//GEN-LAST:event_btReplaceActionPerformed

    private void btReplaceAllActionPerformed(ActionEvent evt) {//GEN-FIRST:event_btReplaceAllActionPerformed
        control.btReplaceAll();
    }//GEN-LAST:event_btReplaceAllActionPerformed

    private void btCancelActionPerformed(ActionEvent evt) {//GEN-FIRST:event_btCancelActionPerformed
        control.btCancel();
    }//GEN-LAST:event_btCancelActionPerformed

    public JCheckBox getCheckMatch() {
        return checkMatch;
    }

    public JTextField getTxtFind() {
        return txtFind;
    }

    public JTextField getTxtReplace() {
        return txtReplace;
    }

    public JButton getBtFind() {
        return btFind;
    }

    public JButton getBtReplace() {
        return btReplace;
    }

    public JButton getBtReplaceAll() {
        return btReplaceAll;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JButton btCancel;
    private JButton btFind;
    private JButton btReplace;
    private JButton btReplaceAll;
    private JCheckBox checkMatch;
    private JLabel jLabel1;
    private JLabel jLabel2;
    private JPanel jPanel1;
    private JTextField txtFind;
    private JTextField txtReplace;
    // End of variables declaration//GEN-END:variables
}
